# Change these first
owner: magnusottosson # Your GitHub organization or username, where this repository lives
repo: portal-status-page-poc # The name of this repository

sites:
  - name: Portal Status Page
    url: https://portal.husqvarnagroup.com/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  themeUrl: https://magnusottosson.github.io/portal-status-page-poc/husqvarna-theme.css
  baseUrl: /portal-status-page-poc
  logoUrl: https://magnusottosson.github.io/portal-status-page-poc/husqvarna-logo.png
  name: Upptime
  introTitle: "Husqvarna Portal Status Page"
  introMessage: "Follow all incidents and issues regarding Husqvarna Portal"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
